//
//  KanaList.swift
//  KanaQuizWatchApp
//
//  Created by Abby Thompson on 23.06.2025.
//
import Foundation

struct Kana: Identifiable {
    let id = UUID()
    let character: String
    let romaji: String
    let type: String // "Hiragana" or "Katakana"
}

let kanaList: [Kana] = [
    // Hiragana - Gojuon
    Kana(character: "あ", romaji: "a", type: "Hiragana"),
    Kana(character: "い", romaji: "i", type: "Hiragana"),
    Kana(character: "う", romaji: "u", type: "Hiragana"),
    Kana(character: "え", romaji: "e", type: "Hiragana"),
    Kana(character: "お", romaji: "o", type: "Hiragana"),
    Kana(character: "か", romaji: "ka", type: "Hiragana"),
    Kana(character: "き", romaji: "ki", type: "Hiragana"),
    Kana(character: "く", romaji: "ku", type: "Hiragana"),
    Kana(character: "け", romaji: "ke", type: "Hiragana"),
    Kana(character: "こ", romaji: "ko", type: "Hiragana"),
    Kana(character: "さ", romaji: "sa", type: "Hiragana"),
    Kana(character: "し", romaji: "shi", type: "Hiragana"),
    Kana(character: "す", romaji: "su", type: "Hiragana"),
    Kana(character: "せ", romaji: "se", type: "Hiragana"),
    Kana(character: "そ", romaji: "so", type: "Hiragana"),
    Kana(character: "た", romaji: "ta", type: "Hiragana"),
    Kana(character: "ち", romaji: "chi", type: "Hiragana"),
    Kana(character: "つ", romaji: "tsu", type: "Hiragana"),
    Kana(character: "て", romaji: "te", type: "Hiragana"),
    Kana(character: "と", romaji: "to", type: "Hiragana"),
    Kana(character: "な", romaji: "na", type: "Hiragana"),
    Kana(character: "に", romaji: "ni", type: "Hiragana"),
    Kana(character: "ぬ", romaji: "nu", type: "Hiragana"),
    Kana(character: "ね", romaji: "ne", type: "Hiragana"),
    Kana(character: "の", romaji: "no", type: "Hiragana"),
    Kana(character: "は", romaji: "ha", type: "Hiragana"),
    Kana(character: "ひ", romaji: "hi", type: "Hiragana"),
    Kana(character: "ふ", romaji: "fu", type: "Hiragana"),
    Kana(character: "へ", romaji: "he", type: "Hiragana"),
    Kana(character: "ほ", romaji: "ho", type: "Hiragana"),
    Kana(character: "ま", romaji: "ma", type: "Hiragana"),
    Kana(character: "み", romaji: "mi", type: "Hiragana"),
    Kana(character: "む", romaji: "mu", type: "Hiragana"),
    Kana(character: "め", romaji: "me", type: "Hiragana"),
    Kana(character: "も", romaji: "mo", type: "Hiragana"),
    Kana(character: "や", romaji: "ya", type: "Hiragana"),
    Kana(character: "ゆ", romaji: "yu", type: "Hiragana"),
    Kana(character: "よ", romaji: "yo", type: "Hiragana"),
    Kana(character: "ら", romaji: "ra", type: "Hiragana"),
    Kana(character: "り", romaji: "ri", type: "Hiragana"),
    Kana(character: "る", romaji: "ru", type: "Hiragana"),
    Kana(character: "れ", romaji: "re", type: "Hiragana"),
    Kana(character: "ろ", romaji: "ro", type: "Hiragana"),
    Kana(character: "わ", romaji: "wa", type: "Hiragana"),
    Kana(character: "を", romaji: "wo", type: "Hiragana"),
    Kana(character: "ん", romaji: "n", type: "Hiragana"),
    // Hiragana - Dakuten
    Kana(character: "が", romaji: "ga", type: "Hiragana"),
    Kana(character: "ぎ", romaji: "gi", type: "Hiragana"),
    Kana(character: "ぐ", romaji: "gu", type: "Hiragana"),
    Kana(character: "げ", romaji: "ge", type: "Hiragana"),
    Kana(character: "ご", romaji: "go", type: "Hiragana"),
    Kana(character: "ざ", romaji: "za", type: "Hiragana"),
    Kana(character: "じ", romaji: "ji", type: "Hiragana"),
    Kana(character: "ず", romaji: "zu", type: "Hiragana"),
    Kana(character: "ぜ", romaji: "ze", type: "Hiragana"),
    Kana(character: "ぞ", romaji: "zo", type: "Hiragana"),
    Kana(character: "だ", romaji: "da", type: "Hiragana"),
    Kana(character: "ぢ", romaji: "ji", type: "Hiragana"),
    Kana(character: "づ", romaji: "zu", type: "Hiragana"),
    Kana(character: "で", romaji: "de", type: "Hiragana"),
    Kana(character: "ど", romaji: "do", type: "Hiragana"),
    Kana(character: "ば", romaji: "ba", type: "Hiragana"),
    Kana(character: "び", romaji: "bi", type: "Hiragana"),
    Kana(character: "ぶ", romaji: "bu", type: "Hiragana"),
    Kana(character: "べ", romaji: "be", type: "Hiragana"),
    Kana(character: "ぼ", romaji: "bo", type: "Hiragana"),
    // Hiragana - Handakuten (Pa-row)
    Kana(character: "ぱ", romaji: "pa", type: "Hiragana"),
    Kana(character: "ぴ", romaji: "pi", type: "Hiragana"),
    Kana(character: "ぷ", romaji: "pu", type: "Hiragana"),
    Kana(character: "ぺ", romaji: "pe", type: "Hiragana"),
    Kana(character: "ぽ", romaji: "po", type: "Hiragana"),
    // Hiragana - Small kana
//    Kana(character: "ぁ", romaji: "xa", type: "Hiragana"),
//    Kana(character: "ぃ", romaji: "xi", type: "Hiragana"),
//    Kana(character: "ぅ", romaji: "xu", type: "Hiragana"),
//    Kana(character: "ぇ", romaji: "xe", type: "Hiragana"),
//    Kana(character: "ぉ", romaji: "xo", type: "Hiragana"),
//    Kana(character: "ゃ", romaji: "xya", type: "Hiragana"),
//    Kana(character: "ゅ", romaji: "xyu", type: "Hiragana"),
//    Kana(character: "ょ", romaji: "xyo", type: "Hiragana"),
//    Kana(character: "っ", romaji: "xtsu", type: "Hiragana"),
//    Kana(character: "ゎ", romaji: "xwa", type: "Hiragana"),

    // Katakana - Gojuon
    Kana(character: "ア", romaji: "a", type: "Katakana"),
    Kana(character: "イ", romaji: "i", type: "Katakana"),
    Kana(character: "ウ", romaji: "u", type: "Katakana"),
    Kana(character: "エ", romaji: "e", type: "Katakana"),
    Kana(character: "オ", romaji: "o", type: "Katakana"),
    Kana(character: "カ", romaji: "ka", type: "Katakana"),
    Kana(character: "キ", romaji: "ki", type: "Katakana"),
    Kana(character: "ク", romaji: "ku", type: "Katakana"),
    Kana(character: "ケ", romaji: "ke", type: "Katakana"),
    Kana(character: "コ", romaji: "ko", type: "Katakana"),
    Kana(character: "サ", romaji: "sa", type: "Katakana"),
    Kana(character: "シ", romaji: "shi", type: "Katakana"),
    Kana(character: "ス", romaji: "su", type: "Katakana"),
    Kana(character: "セ", romaji: "se", type: "Katakana"),
    Kana(character: "ソ", romaji: "so", type: "Katakana"),
    Kana(character: "タ", romaji: "ta", type: "Katakana"),
    Kana(character: "チ", romaji: "chi", type: "Katakana"),
    Kana(character: "ツ", romaji: "tsu", type: "Katakana"),
    Kana(character: "テ", romaji: "te", type: "Katakana"),
    Kana(character: "ト", romaji: "to", type: "Katakana"),
    Kana(character: "ナ", romaji: "na", type: "Katakana"),
    Kana(character: "ニ", romaji: "ni", type: "Katakana"),
    Kana(character: "ヌ", romaji: "nu", type: "Katakana"),
    Kana(character: "ネ", romaji: "ne", type: "Katakana"),
    Kana(character: "ノ", romaji: "no", type: "Katakana"),
    Kana(character: "ハ", romaji: "ha", type: "Katakana"),
    Kana(character: "ヒ", romaji: "hi", type: "Katakana"),
    Kana(character: "フ", romaji: "fu", type: "Katakana"),
    Kana(character: "ヘ", romaji: "he", type: "Katakana"),
    Kana(character: "ホ", romaji: "ho", type: "Katakana"),
    Kana(character: "マ", romaji: "ma", type: "Katakana"),
    Kana(character: "ミ", romaji: "mi", type: "Katakana"),
    Kana(character: "ム", romaji: "mu", type: "Katakana"),
    Kana(character: "メ", romaji: "me", type: "Katakana"),
    Kana(character: "モ", romaji: "mo", type: "Katakana"),
    Kana(character: "ヤ", romaji: "ya", type: "Katakana"),
    Kana(character: "ユ", romaji: "yu", type: "Katakana"),
    Kana(character: "ヨ", romaji: "yo", type: "Katakana"),
    Kana(character: "ラ", romaji: "ra", type: "Katakana"),
    Kana(character: "リ", romaji: "ri", type: "Katakana"),
    Kana(character: "ル", romaji: "ru", type: "Katakana"),
    Kana(character: "レ", romaji: "re", type: "Katakana"),
    Kana(character: "ロ", romaji: "ro", type: "Katakana"),
    Kana(character: "ワ", romaji: "wa", type: "Katakana"),
    Kana(character: "ヲ", romaji: "wo", type: "Katakana"),
    Kana(character: "ン", romaji: "n", type: "Katakana"),
    // Katakana - Dakuten
    Kana(character: "ガ", romaji: "ga", type: "Katakana"),
    Kana(character: "ギ", romaji: "gi", type: "Katakana"),
    Kana(character: "グ", romaji: "gu", type: "Katakana"),
    Kana(character: "ゲ", romaji: "ge", type: "Katakana"),
    Kana(character: "ゴ", romaji: "go", type: "Katakana"),
    Kana(character: "ザ", romaji: "za", type: "Katakana"),
    Kana(character: "ジ", romaji: "ji", type: "Katakana"),
    Kana(character: "ズ", romaji: "zu", type: "Katakana"),
    Kana(character: "ゼ", romaji: "ze", type: "Katakana"),
    Kana(character: "ゾ", romaji: "zo", type: "Katakana"),
    Kana(character: "ダ", romaji: "da", type: "Katakana"),
    Kana(character: "ヂ", romaji: "ji", type: "Katakana"),
    Kana(character: "ヅ", romaji: "zu", type: "Katakana"),
    Kana(character: "デ", romaji: "de", type: "Katakana"),
    Kana(character: "ド", romaji: "do", type: "Katakana"),
    Kana(character: "バ", romaji: "ba", type: "Katakana"),
    Kana(character: "ビ", romaji: "bi", type: "Katakana"),
    Kana(character: "ブ", romaji: "bu", type: "Katakana"),
    Kana(character: "ベ", romaji: "be", type: "Katakana"),
    Kana(character: "ボ", romaji: "bo", type: "Katakana"),
    // Katakana - Handakuten (Pa-row)
    Kana(character: "パ", romaji: "pa", type: "Katakana"),
    Kana(character: "ピ", romaji: "pi", type: "Katakana"),
    Kana(character: "プ", romaji: "pu", type: "Katakana"),
    Kana(character: "ペ", romaji: "pe", type: "Katakana"),
    Kana(character: "ポ", romaji: "po", type: "Katakana"),
    // Katakana - Small kana
//    Kana(character: "ァ", romaji: "xa", type: "Katakana"),
//    Kana(character: "ィ", romaji: "xi", type: "Katakana"),
//    Kana(character: "ゥ", romaji: "xu", type: "Katakana"),
//    Kana(character: "ェ", romaji: "xe", type: "Katakana"),
//    Kana(character: "ォ", romaji: "xo", type: "Katakana"),
//    Kana(character: "ャ", romaji: "xya", type: "Katakana"),
//    Kana(character: "ュ", romaji: "xyu", type: "Katakana"),
//    Kana(character: "ョ", romaji: "xyo", type: "Katakana"),
//    Kana(character: "ッ", romaji: "xtsu", type: "Katakana"),
//    Kana(character: "ヮ", romaji: "xwa", type: "Katakana"),
//    Kana(character: "ヵ", romaji: "xka", type: "Katakana"),
//    Kana(character: "ヶ", romaji: "xke", type: "Katakana")
]

